### ISSUE TITLE
replace maven by gradle

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#143]
Replace maven-build by Gradle. Update also the GitHub Actions.

**Comment by utsav00** [comment]
Is this open to get assigned and worked on or since there is a hacktoberfest label, this will only be open in October?

**Comment by stritti** [comment]
It is open. It is just suggested for Hacktoberfest. Every support is welcome.

**Comment by utsav00** [comment]
Okay, thanks for clarifying. I'll take this up
