### ISSUE TITLE
Seperate estimation for FE and BE per Story

### ISSUE THREAD

**Issue by fgn-sybit** [Sybit-Education/Diveni#155]
My three latest projects had 2 custom fields per Story:
- Storypoints for FE
- Storypoints for BE

The combined Storypoints were written to the usual field, but weren't necessarily a fibonacci-number anymore.

Planningpoker doesn't provide a solution for this.
My suggestion:
Option: "seperate Estimate" => You can configure (or pick them out of custom fields from jira) multiple Storypoint-Fields per Story
These "sub-estimations" are automatically entered into the jira custom fields
If all sub-estimations are done a dialog pops up for entering the combined story estimation

**Comment by stritti** [comment]
Thanks for your proposal. This is not a common workflow and we will not add this special case.
If you have further improvemnts, let us know!
