### ISSUE TITLE
Lack of responsive design

### ISSUE THREAD

**Issue by KzuDemEvin** [Sybit-Education/Diveni#191]
When using Diveni on a mobile phone it is clear that this site is not optimized for an mobile device.

**Comment by TheInspiredConjurer** [comment]
Since no one is working on this, I would like to work on this by integrating tailwind

**Comment by stritti** [comment]
Hi @TheInspiredConjurer we would be happy if you could support us. 
Is it really required to add tailwindCSS (really cool, no mind) in addition to existing BoostrapVue, which already provides a lot for responsive design?

**Comment by TheInspiredConjurer** [comment]
Not really, no...

but I dont know bootstrap vue. :(
