### ISSUE TITLE
API: Migrate Springfox to Springdoc

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#208]
See https://stackoverflow.com/questions/70178343/springfox-3-0-0-is-not-working-with-spring-boot-2-6-0
and https://springdoc.org/#migrating-from-springfox

**Comment by aman2457** [comment]
Hey @stritti , I'm planning to pick few of the issue to contribute. I'm not sure whether to assign it right away or wait till the start of hacktober fest.

**Comment by stritti** [comment]
> Hey @stritti , I'm planning to pick few of the issue to contribute. I'm not sure whether to assign it right away or wait till the start of hacktober fest.

Hey @aman2457, it is my first hacktoberfest participating.  Maybe you set up your environment and when hacktoberfest is started you could open the PRs. Diveni has no big publicity and I think there is no danger to do double work.
BTW: if you have additional improvements, just add them as issue.

**Comment by aman2457** [comment]
Hey @stritti ,
Thank you for such a quick response.
I'll have a look at the codebase and will try to run this locally.

**Comment by stritti** [comment]
Looking forward your work. Do not hesitate to ask if you have open questions. Documents still needs improvements.

**Comment by christian-german** [comment]
Hi,
may I take this one? The project is up and running on my dev environment, SpringFox is responding correctly. This should take too much time to migrate to spring-doc (change the pom and remove the Docklet from the configuration)

**Comment by stritti** [comment]
What is your progress @aman2457? Could you give @christian-german feedback?

BTW we have updated now to gradle build environment by  pull request: https://github.com/Sybit-Education/Diveni/pull/227

**Comment by aman2457** [comment]
Hey @stritti , Sorry didn't get too much time for this,
may be you can give this task to @christian-german.

**Comment by stritti** [comment]
I currently tested the main branch upgrading to spring-boot `v2.7.4`: the backend still crashes then. 
Would be nice if you could solve this issue @christian-german .
