### ISSUE TITLE
Configuration setup

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#209]
Configuration of the App should be able during setup process.
Currently the environment has to be setup during `docker compose`. This should be possible within administration ui. Also the configuration should be changeable after system is already installed.

For example:
* Settings of JIRA server/cloud
* name/base-URL of server
* See also https://github.com/Sybit-Education/Diveni/blob/main/docs/guide/install.md

The configuration could be done by CLI or web-based UI.

**Comment by KzuDemEvin** [comment]
In addition to that:

It is currently not possible to edit the `env.` for the frontend `(/frontend/.env)` if the application is deployed via the pre-built docker images from GitHub. The only way to do so is to edit the `.env` and to build the application via the `docker-compose.dev.yml` yourself.

This should maybe be possible within the docker-compose itself.

**Comment by stritti** [comment]
> 

Maybe we could also transfer these configuations to the backend and request them via REST-Services?

**Comment by KzuDemEvin** [comment]
> > 
> 
> Maybe we could also transfer these frontend configuations to the backend and request them via REST-Services?

Yes, I think some of [them](https://github.com/Sybit-Education/Diveni/blob/main/frontend/.env) could be moved to the backend.
e.g.:
```
VUE_APP_ENABLE_JIRA_CLOUD
VUE_APP_ENABLE_JIRA_SERVER
VUE_APP_JIRA_CLOUD_AUTHORIZE_URL
```
But they have to be sent to the user everytime he loads the site.

`VUE_APP_SERVER_API_URL` is set to `/api`. I think this is only needed if the application runs in docker. In an development requirement it has to be set differently.

**Comment by stritti** [comment]
Yes and the fallback languages could be hard coded to `en` I think.

**Comment by stritti** [comment]
I would like to suggest:
* add `spring-boot-admin` (sba) using a separate docker container: https://github.com/slydeveloper/spring-boot-admin-docker
* configure Diveni backend to be a sba client
* expose configurations via JMX(?)

Then we could start/stop spring boot admin container only when required to change configs.
We have then to ad routing to proxy for sba.

**Comment by KzuDemEvin** [comment]
Hi @stritti,

I tried `spring-boot-admin` out and in my opinion is seems to be too overkill for Diveni. It is useful if you are dealing with multiple instances.
I think it is easier to manage the environment variables directly in docker compose or via a .env-file.

- As a sba client you are exposing critical data
- sba has to be stopped manually and always started when needed
- It is easier to just edit the docker compose or .env file
- I was able to view the configuration but I was not able to edit them
- **Disadvantage of not using sba:** No configuration changes while Diveni is running

**Comment by stritti** [comment]
> Hi @stritti,
> 
> I tried `spring-boot-admin` out and in my opinion is seems to be too overkill for Diveni. It is useful if you are dealing with multiple instances. I think it is easier to manage the environment variables directly in docker compose or via a .env-file.
> 
> * As a sba client you are exposing critical data
> * sba has to be stopped manually and always started when needed
> * It is easier to just edit the docker compose or .env file
> * I was able to view the configuration but I was not able to edit them
> * **Disadvantage of not using sba:** No configuration changes while Diveni is running

Okay i see. I think then we should have a bulled proved docker compose setup :)
