### ISSUE TITLE
Fontend: migrate from vuex to Pinia

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#212]
Update the vue.js frontend to use [Pinia](https://pinia.vuejs.org/) instead of vuex.

See also: https://pinia.vuejs.org/cookbook/migration-vuex.html

**Comment by ravihidayat** [comment]
Looks interesting, I might be able to pick this up. But I assume I also need to figure out #219, no?

**Comment by stritti** [comment]
> Looks interesting, I might be able to pick this up. But I assume I also need to figure out #219, no?

Yes I think they are somehow in connection. Pinia could be used with vue2 too, but the migration of vue2 to vue 3 might be a bigger thing.

**Comment by ravihidayat** [comment]
I would be happy to support. I think we could start with https://v3-migration.vuejs.org/migration-build.html, as I think using @vue/compat is the way to go for now.

**Comment by stritti** [comment]
Yes this is seems to be a good starting point. I think biggest issue will be BoostrapVue. There is already a fork for vue3 but not everything is supported currently: https://github.com/bootstrap-vue/bootstrap-vue/issues/5196

**Comment by ravihidayat** [comment]
Seems like there will be no BootstrapVue 3 in the near future, but the fork that you mentioned should be worth trying. What's your call? Should we try that out?

**Comment by stritti** [comment]
> Seems like there will be no BootstrapVue 3 in the near future, but the fork that you mentioned should be worth trying. What's your call? Should we try that out?

I think we should discuss this in #219

**Comment by stritti** [comment]
Also done by https://github.com/Sybit-Education/Diveni/issues/219
