### ISSUE TITLE
GitHub Actions: Clean up

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#215]
There are several GitHub Actions which do almost the same. Sometimes it looks like that they break each other (rerun solves errors).
The actions should be simplified and cleaned.

**Comment by stritti** [comment]
Some Actions have to be restricted to main branch and the origin repository to prevent failing on branched repos.

**Comment by KzuDemEvin** [comment]
Hi @stritti,

there are multiple ways to change the deployment:

1. Global deployment workflow
>- One workflow that manages the build and deploy process for each service
>- The workflow runs by pushing on the main branch
>- The workflow must check the changed files for each service and then build and deploy a Docker image only when changes are made.
>- Advantage: Only deploying when all images are built (no need to check via API if jobs are done)
>- Advantage: No need to run tests on main branch
2. Separate deployment workflow for each service
>- Each workflow handles its deployment separately
>- The workflow has to differentiate between a push to the main branch or a pull-request
>- Only recreate the Docker container that changed

I would personally go with 1. What is your opinion?

**Comment by stritti** [comment]
> Hi @stritti,
> 
> there are multiple ways to change the deployment:
> 
> 1. Global deployment workflow
> 
> > * One workflow that manages the build and deploy process for each service
> > * The workflow runs by pushing on the main branch
> > * The workflow must check the changed files for each service and then build and deploy a Docker image only when changes are made.
> > * Advantage: Only deploying when all images are built (no need to check via API if jobs are done)
> > * Advantage: No need to run tests on main branch
> 
> 2. Separate deployment workflow for each service
> 
> > * Each workflow handles its deployment separately
> > * The workflow has to differentiate between a push to the main branch or a pull-request
> > * Only recreate the Docker container that changed
> 
> I would personally go with 1. What is your opinion?

Yes i think option 1 would be better
