### ISSUE TITLE
Automatically show results upon last vote

### ISSUE THREAD

**Issue by erikhubers** [Sybit-Education/Diveni#229]
First of all, thank you for creating this amazing looking planning poker tool!

**Is your feature request related to a problem? Please describe.**
Currently it's only possible to define a maximum time for each estimation. When the time is over, it will show the results automatically.
It will always wait for the estimation timer to expire before showing the results automatically, even if all members have voted before the timer expires. This adds additional delay or needs manual intervention (by the host pressing 'show results' manually each time).

**Describe the solution you'd like**
I would love the results to also show automatically when all votes are in, without waiting for the timer to expire.

**Comment by stritti** [comment]
Thanks for your suggestion, @erikhubers. We had this discussed  too. 
One part of the team wanted to wait until time is over to have time to correct the vote. But doing several plannings now it is almost every vote I click `show results` to shorten the time. 
INHO if someone wants to update his vote he has the chance in additional round.

We should improve like suggested.

**Comment by sourabhkashyap95** [comment]
Hi @stritti, I am planning to work on this.
One approach is to introduce a new boolean field in the Session object which will be calculated on every "/vote" to identify whether all members submitted their vote.
Another way, I am thinking if we can compare the size of the member list and the memberVoted map size and take all members are done with voting when sizes are equal.

Please suggest.
Thanks

**Comment by stritti** [comment]
Hi @sourabhkashyap95, looking forward your PR!

I think the second proposal is more robust. Sure someone could leave the session, but then the Scrum Master could force showing result by using "show results" button any more. 
I will assign the issue to you.

**Comment by sourabhkashyap95** [comment]
Hi @stritti ,  Can you please review this [PR](https://github.com/Sybit-Education/Diveni/pull/240) and tag this issue?

**Comment by sourabhkashyap95** [comment]
@stritti I have reopened the [PR](https://github.com/Sybit-Education/Diveni/pull/244) for the above feature, I have tested it locally, and working fine for me.
Feature description:
As soon as the last member finishes voting, overall voting will be finished and results will be shown to all members and admin/host.
