### ISSUE TITLE
Current active Sessions

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#246]
**Is your feature request related to a problem? Please describe.**

Show number of current active planning sessions to know if an update could be done.

**Describe the solution you'd like**

On the homepage it should be shown how many planning sessions are active as sum. 
(Probably also the number of users within these sessions).

**Additional context**

It is at the moment dangerous to make updates, because we do not know if someone is using the app at this moment.

**Comment by Valeri12580** [comment]
Hi @stritti, can I start working on this issue?

**Comment by SponsoredByPuma** [comment]
Hi @Valeri12580, this issue is already done. The PR just needs to be merged.
