### ISSUE TITLE
Add GitHub to top menu bar

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#247]
**Is your feature request related to a problem? Please describe.**
GitHub icon in top menu bar to link to sources to show directly oss background.

**Comment by Aspireve** [comment]
Hi @stritti could I work on this issue. I'll complete it quick.

**Comment by stritti** [comment]
Hi @Aspireve sure, I assign it to you! 💚

**Comment by Aspireve** [comment]
Hi!! @stritti 
on running the frontend part of the project with the commands `npm install`, `npm run serve` I found this screen
![image](https://user-images.githubusercontent.com/93852415/198316924-7cb6f02a-cd7e-48db-80ed-224d79d73db3.png)

Which is very different than the website screen.
Is there something im missing while running it

**Comment by stritti** [comment]
> Hi!! @stritti on running the frontend part of the project with the commands `npm install`, `npm run serve` I found this screen ![image](https://user-images.githubusercontent.com/93852415/198316924-7cb6f02a-cd7e-48db-80ed-224d79d73db3.png)
> 
> Which is very different than the website screen. Is there something im missing while running it

Hi @Aspireve,
this ist the screen of the app itself.  That is the correct one. I think between "New Session" and the Language-Selector could be a nice place for the GitHub-Icon.

Probably you have seen the page of documentation at https://ocs.diveni.io ?

**Comment by Aspireve** [comment]
> > Hi!! @stritti on running the frontend part of the project with the commands `npm install`, `npm run serve` I found this screen ![image](https://user-images.githubusercontent.com/93852415/198316924-7cb6f02a-cd7e-48db-80ed-224d79d73db3.png)
> > Which is very different than the website screen. Is there something im missing while running it
> 
> Hi @Aspireve, this ist the screen of the app itself. That is the correct one. I think between "New Session" and the Language-Selector could be a nice place for the GitHub-Icon.
> 
> Probably you have seen the page of documentation at https://docs.diveni.io ?

Ohh I thought it was different cause the one I could view after opening the website was different [Diveni Website](https://sybit-education.github.io/Diveni/) [taken from the repos ReadMe.md]
Ill do that fast then

**Comment by Aspireve** [comment]
## Development Update
Hi @stritti!!
I managed to get the GitHub image and load the GitHub Source Code on pressing it. Is it cool?
Find below the attached video preview of the website

https://user-images.githubusercontent.com/93852415/198349634-10fb0aad-046b-428b-ace1-efd3ada78c84.mp4

**Comment by stritti** [comment]
Hi @Aspireve, really great 👍🏼 could you align it to be horizontal middle aligned to the button left and drop-down right side? Maybe you have to add a nav-item around the icon.

**Comment by Aspireve** [comment]
Hi @stritti 
Is this fine?

https://user-images.githubusercontent.com/93852415/198379102-822f0f95-1010-4002-a3c7-d37a9727fd89.mp4

**Comment by stritti** [comment]
> Hi @stritti 
> 
> Is this fine?
> 
> 
> 
> https://user-images.githubusercontent.com/93852415/198379102-822f0f95-1010-4002-a3c7-d37a9727fd89.mp4
> 
> 
Yeah, awesome 💚 Open your PR, I will approve it. Many thanks for your support, @Aspireve
