### ISSUE TITLE
Starting new session while another is active

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#291]
**Describe the bug**
If you start a new session while there is already a planning session is running as organizer, the team list is already filled by ghost users from previous session.

**To Reproduce**
1. Start a planning session
2. invite team
3. do plannings
4. start new session without stopping current session
5. share and invite to session

**Expected behavior**
The list of team members should be cleared and new session should be started clean.

**Comment by KzuDemEvin** [comment]
The changes made in #293 break the ability to import user stories. This is why I reverted the changes, restored the branch and reopened this issue.
@SponsoredByPuma feel free to take a look and maybe fix this issue. Otherwise you can de-assign yourself.

**Comment by SponsoredByPuma** [comment]
@KzuDemEvin Alright I'll take a look at it.
