### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by johnfelipe** [Sybit-Education/Diveni#326]
I want to contribute for translate strings to Spanish and french

**Comment by KzuDemEvin** [comment]
Hi @johnfelipe, 
thank you for your interest in supporting Diveni! :)
Contributions to i18n are handled by Crowdin.

Here are some appropriate URLs:
- [Diveni on Crowdin](https://crowdin.com/project/diveni)
- [French translation](https://crowdin.com/translate/diveni/36/en-fr)
- [Spanish translation](https://crowdin.com/translate/diveni/36/en-es)

If you need help, feel free to comment or join our Discord :)
