### ISSUE TITLE
Azure DevOPS integration

### ISSUE THREAD

**Issue by johnfelipe** [Sybit-Education/Diveni#342]
Is possible add azure devops integration?

**Comment by KzuDemEvin** [comment]
Hi @johnfelipe,
Azure DevOps is already integrated:
* [Create Azure DevOps PAT](https://sybit-education.github.io/Diveni/guide/install#azure-devops-connector)
* [Deploy Diveni with PAT](https://sybit-education.github.io/Diveni/guide/install#add-configuration-to-the-diveni-instance)

For now it is required to self host Diveni to use Azure DevOps, just like Jira Server and Jira Cloud. 
Azure DevOps integration using OAuth is already on the list: see #299

If you need need any help feel free to contact us on our [Discord](https://discord.gg/7JmRyn5dc6).
