### ISSUE TITLE
Upgrade to Java 20

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#379]
**Is your feature request related to a problem? Please describe.**

Java 11 is quite old and we should update to latest version of Java.

**Describe the solution you'd like**

Backend Build should be upgraded to Java 20:

* Gradle Build
* GitHub Actions
* Docker images

**Comment by KzuDemEvin** [comment]
What about choosing LTS versions of Java? The current one is 17, and the next one will be 21, I think.

**Comment by stritti** [comment]
This is good input, yes, LTE is the better choice!
