### ISSUE TITLE
Admins page freezes/crashes after all members have left the session

### ISSUE THREAD

**Issue by Dan1elBox** [Sybit-Education/Diveni#394]
**Describe the bug**
After a planning session, when all members have left, the admin's browser freezes/crashes and Diveni becomes unresponsive.

**To Reproduce**

1. Go to https://diveni.io
2. Start a new Session
3. Invite a few members
4. Play one or more rounds of Planning Poker
5. Exit the session with all members.
6. See how the Diveni page freezes and becomes unresponsive for the Session-admin.

**Expected behavior**
It should be possible for the admin to continue the session after all members have left, to reconnect to the session, or if necessary, to start a new session again without Diveni/Bowser freezing/crashing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome & Edge

**Additional context**
The error has been reproduced so far on https://diveni.io/, https://dev.diveni.io, and using a local Docker setup. 
However, this error does NOT occur when starting the application locally without Docker.

**Comment by SponsoredByPuma** [comment]
I think this issue should be fixed with this PR: https://github.com/Sybit-Education/Diveni/pull/392

**Comment by KzuDemEvin** [comment]
Fixed in #392
