### ISSUE TITLE
Create a News-Page and attach it to the Router

### ISSUE THREAD

**Issue by SponsoredByPuma** [Sybit-Education/Diveni#409]
**Describe the solution you'd like**
We want to create a news page for Diveni. This would be the very first step to it.
Create a new Page and attach it to the router.

**Comment by ShatilKhan** [comment]
Can I please take on this issue?
I've done some frontend contributions before

**Comment by Valeri12580** [comment]
Hello, I stated the whole milestone and it should be done today
