### ISSUE TITLE
Create a button on the landing page redirecting to the news page

### ISSUE THREAD

**Issue by SponsoredByPuma** [Sybit-Education/Diveni#410]
**Describe the solution you'd like**
To get to the news page, we need a button to get there.

**Describe alternatives you've considered**
The button could also be placed on the footer of Diveni or inside the Navigation Bar.

**Comment by nikhilgarg26** [comment]
hey @SponsoredByPuma where can we find footer of Diveni ? I am new to open source, it would be great if you could help

**Comment by SponsoredByPuma** [comment]
hey @nikhilgarg26,
the footer can be found under frontend/src/components/navigation

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by Valeri12580** [comment]
Hello, I stated the whole milestone and it should be done today
