### ISSUE TITLE
Functionality of the News Page

### ISSUE THREAD

**Issue by SponsoredByPuma** [Sybit-Education/Diveni#412]
**Is your feature request related to a problem? Please describe.**
Now that our page has been styled we would like to give it some functionality.

**Describe the solution you'd like**
We would like to have an text area where the user can see which changes have been made to Diveni.
It would be pretty good to attach this text area to the GitHub Pull Requests which have been merged, so it updates the text area automatically.

**Comment by Valeri12580** [comment]
> **Is your feature request related to a problem? Please describe.** Now that our page has been styled we would like to give it some functionality.
> 
> **Describe the solution you'd like** We would like to have an text area where the user can see which changes have been made to Diveni. It would be pretty good to attach this text area to the GitHub Pull Requests which have been merged, so it updates the text area automatically.

What exactly from the pull request should be displayed in the mentioned area? Maybe the title or?

**Comment by SponsoredByPuma** [comment]
Hi @Valeri12580,
I think the title would be a pretty good start tbh.

**Comment by Valeri12580** [comment]
Hi @SponsoredByPuma ,
what do you think about this?
<img width="1106" alt="image" src="https://github.com/Sybit-Education/Diveni/assets/49874855/a9075b3c-7d75-45f9-9ce2-5c372fe7fbd0">

The header will be the date, the title will be the PR title and the "Link" will be link to the PR or the issue

**Comment by SponsoredByPuma** [comment]
I think that's a good idea.
Could you also attach the mockup to this issue: https://github.com/Sybit-Education/Diveni/issues/411

**Comment by Valeri12580** [comment]
Hi @SponsoredByPuma, 
I have two important questions: 
1. Which PR's should be showed to the new page. In my opinion only those who are closed and merged.
2. There are some PR's which doesn't have any meaning to the end user. For example: 
<img width="1253" alt="image" src="https://github.com/Sybit-Education/Diveni/assets/49874855/0c3d3c3c-e3d8-4b8f-8561-6bdededeca4f">

My suggestion is to think about way to filter those PRs

**Comment by Valeri12580** [comment]
Hello, I stated the whole milestone and it should be done today

**Comment by SponsoredByPuma** [comment]
Hey @Valeri12580,
I think both of your points are valid.
Maybe it is possible to filter the pull requests made by the dependabot.

**Comment by Valeri12580** [comment]
> Hey @Valeri12580, I think both of your points are valid. Maybe it is possible to filter the pull requests made by the dependabot.

I will think about possible solution. Can you assign the whole milestone to me?

**Comment by Valeri12580** [comment]
> Hey @Valeri12580, I think both of your points are valid. Maybe it is possible to filter the pull requests made by the dependabot.

I implemented functionality which filter the user type (bot) from the results. This way the page will show only PRs made by users. I believe that this functionality can be improved in the future to show only PRs with particular tags (feature,bugfix, etc..)

**Comment by SponsoredByPuma** [comment]
That's great. I'm looking forward to it :)

**Comment by Valeri12580** [comment]
@SponsoredByPuma The only thing that is remaining are some unit tests. Tomorrow I will create PR which will contain everything from the whole milestone :)
