### ISSUE TITLE
Feedback button

### ISSUE THREAD

**Issue by SponsoredByPuma** [Sybit-Education/Diveni#418]
**Is your feature request related to a problem? Please describe.**
As a developer, you want to get as much feedback as possible. Currently there is no way to get any feedback.

**Describe the solution you'd like**
We could add a feedback button with an input field for detailed feedback to the member voting page and also to the admin page.

**Describe alternatives you've considered**
We could also create a completly new page and put its navigation link in the footer or in the navigation bar.

**Comment by stritti** [comment]
I would like to suggest to use a open source 3rd-party service for the feedback instead of implementing it in diveni. Let us be focused on product planning poker.

Probably we could add another Docker-Container with an existing service for that or yust refer a running service like tawk.to or chatwoot.

First we should investigat in pros/cons of existing services.

**Comment by Valeri12580** [comment]
Hi @SponsoredByPuma, can I start working on this feature?

**Comment by SponsoredByPuma** [comment]
Hey @Valeri12580,
you can start working on this issue.
We would like to have a button, which redirects the user to this github page:
![image](https://github.com/Sybit-Education/Diveni/assets/92574150/350827af-4029-4085-959a-d2002becdac2)

You can choose on where to place the button and how to style it, have fun :)

**Comment by stritti** [comment]
Hi @Valeri12580, 
I think the new button causes now another problem: https://github.com/Sybit-Education/Diveni/issues/493 
Probably you could solve this?

**Comment by Valeri12580** [comment]
> Hi @Valeri12580, I think the new button causes now another problem: #493 Probably you could solve this?

Hi, @stritti 
I mentioned the reason for the problem in [https://github.com/Sybit-Education/Diveni/issues/493](url)

I will fix it.
