### ISSUE TITLE
Resolve the Lint Issues / Warnings

### ISSUE THREAD

**Issue by SponsoredByPuma** [Sybit-Education/Diveni#428]
When starting the frontend server, you get a lint message, with all ~ 4700 issues / warnings.

We should remove these issues / warnings, since it makes everything quite confusing and it is hard to spot new issues

**Comment by SponsoredByPuma** [comment]
About 99% of the warnings can be fixed with this command: **_npx prettier --write ._**

**Comment by SponsoredByPuma** [comment]
sure, here is a small snippet of the warnings: 
![image](https://github.com/Sybit-Education/Diveni/assets/92574150/6b881a1f-a3eb-4393-9793-990088a6f733)

**Comment by stritti** [comment]
I think there is on someones machine an automatically change of Unix-style line break to Windows-style. 
I noticed this to, when checking out on Windows, but have not found the automatism. It is the changes of CR to CR/LF.
