### ISSUE TITLE
User Roles and Permissions

### ISSUE THREAD

**Issue by Dan1elBox** [Sybit-Education/Diveni#433]
### IMPORTANT NOTE: This issue/feature request has not yet received approval from the project owner and should not be worked on at this time!!!

**Feature Request:**
To enhance the flexibility and control of our Planning Poker app, I suggest the implementation of user roles and permissions.
This feature will distribute the work that would typically be solely handled by the session admin.

With user roles and permissions, session administrators will have the ability to assign and manage various user roles, including Moderators and Participants, while also defining their specific permissions.
These permissions will prove especially valuable for tasks such as user story creation, removing Participants, and, potentially, moderating chat discussions (Pull Request: Feature/413 chat room #419).

This enhancement will empower our Planning Poker app to provide a more structured and customizable experience for users, ultimately streamlining the estimation and collaboration process.

**Comment by stritti** [comment]
I think we should discuss this at maintainers board. It would change the app massive.

**Comment by Dan1elBox** [comment]
@stritti I agree. It would involve a significant effort, and the benefits probably don't justify this feature.
