### ISSUE TITLE
ChatGPT justifications/explanations for User Story Estimation

### ISSUE THREAD

**Issue by Dan1elBox** [Sybit-Education/Diveni#436]
### IMPORTANT NOTE: This issue/feature request has not yet received approval from the project owner and should not be worked on at this time!!!

**Feature Request:**
Building upon the ChatGPT feature for user story estimation in our Planning Poker app, I suggest the implementation of an additional feature. 
This feature would involve ChatGPT providing justifications/explanation for the estimations and displaying these explanation in the chat which is based on pullrequest: Feature/413 chat room #419

**Comment by stritti** [comment]
Sounds interesting. Could you provide more details? Probably an example how it could work?
Any suggestions or ideas from the audience?
