### ISSUE TITLE
Multilingual Support Expansion

### ISSUE THREAD

**Issue by Dan1elBox** [Sybit-Education/Diveni#437]
### IMPORTANT NOTE: This issue/feature request has not yet received approval from the project owner and should not be worked on at this time!!!

**Feature Request:**
To further enhance the accessibility and inclusivity of our Planning Poker app, we encourage contributors to expand multilingual support. 
The app is currently available in the following languages:

- German
- French
- Italian
- Polish
- Portuguese
- Spanish
- Ukrainian

This initiative aims to make the app more accessible to a broader user base across various regions.

**Comment by stritti** [comment]
@Dan1elBox propably you could create for every existing language an issue to improve these translations. Reference to crowdin should be mentioned. That service is master of transportations.

**Comment by Dan1elBox** [comment]
Hi @stritti, good point, I'll get to it in the coming days.
