### ISSUE TITLE
Progressive Web App: Name and Icons missing

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#438]
**Describe the bug**
If I add Diveni to home screen it has not correct name and no icon. See attached screenshot:
![image](https://github.com/Sybit-Education/Diveni/assets/184547/e3439c6f-4475-4c8b-9dd3-d241c84744b2)

**To Reproduce**
1. Open diveni.io on smartphone
2. Click on 'add to Home screen'
3. See error

**Expected behavior**
App name: Diveni.io
App logo: the green cards

**Screenshots**
See above.

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: iOS17
 - Browser: Safari, Chrome
 - Version

**Comment by stritti** [comment]
See also: https://github.com/Sybit-Education/Diveni/issues/207

**Comment by annezel** [comment]
Could I try it?

**Comment by stritti** [comment]
Sure, @annezel. I assign it to you. Looking forward your work!
