### ISSUE TITLE
Fix the font color of the text area on the member page.

### ISSUE THREAD

**Issue by SponsoredByPuma** [Sybit-Education/Diveni#454]
**Describe the bug**
The font color does not change when switching between the two themes.

**To Reproduce**
1. Create a session
2. invite your members
3. create a user story with a description
4. the font color of the description, on the member vote page, does not switch colors. 

**Expected behavior**
The color should be white in dark mode and black in light mode.

**Screenshots**
![image](https://github.com/Sybit-Education/Diveni/assets/92574150/f3e11fe5-a817-430a-905f-f9a2984fa810)

**Comment by shinebhatta** [comment]
Can you please assign me this issue?
