### ISSUE TITLE
Github action "backend" failing for forked repositories

### ISSUE THREAD

**Issue by Valeri12580** [Sybit-Education/Diveni#456]
**Describe the bug**
The github action "backend" is failing when the jobs "Test" and "formatting" are triggered for PRs from forked repositories. Example:
https://github.com/Sybit-Education/Diveni/actions/runs/6560803558/job/17819310837#step:5:21

**To Reproduce**
1. Trigger the jobs for backend github action

**Expected behavior**
The mentioned jobs above are failing

**Screenshots**
<img width="1233" alt="image" src="https://github.com/Sybit-Education/Diveni/assets/49874855/8235e735-8b80-41bd-87ab-6e089c919bdc">

<img width="1229" alt="image" src="https://github.com/Sybit-Education/Diveni/assets/49874855/834f1999-b0aa-4c71-b207-45456bb4c202">

**Comment by stritti** [comment]
@Valeri12580 could you try to merge my branch with the changes and verify if it works now?

**Comment by Valeri12580** [comment]
> @Valeri12580 could you try to merge my branch with the changes and verify if it works now?


https://github.com/Sybit-Education/Diveni/actions/runs/6597906564/job/17941827635?pr=426
https://github.com/Sybit-Education/Diveni/actions/runs/6597906565/job/17941827562?pr=426

It looks like the formatting job is fixed but the "Test" from backend and Lint from frontend are still failling.

<img width="1089" alt="image" src="https://github.com/Sybit-Education/Diveni/assets/49874855/5941be04-0a30-45ad-8783-97266890a7ea">

<img width="1263" alt="image" src="https://github.com/Sybit-Education/Diveni/assets/49874855/2539ae36-7ea3-4221-be07-af1e3e7512eb">

**Comment by stritti** [comment]
Hi @Valeri12580 oh, yes. I check this.

**Comment by Valeri12580** [comment]
Hi @stritti, It looks like this job is failing too: 
https://github.com/Sybit-Education/Diveni/actions/runs/6597906565/job/17941827562?pr=426

I'm not sure why it is failing but I see that you added it recently

**Comment by stritti** [comment]
Hi @Valeri12580  I created now a fork for better verification. 


What you noted at https://github.com/Sybit-Education/Diveni/issues/456#issuecomment-1778949360 is caused by warnings in frontend. I solved this in the new PR too: https://github.com/Sybit-Education/Diveni/pull/483
