### ISSUE TITLE
Connector: GitHub issues

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#480]
**Is your feature request related to a problem? Please describe.**

An additional connector  to do Planning Poker using issues of GitHub.

**Describe the solution you'd like**

It should be possible to configure GitHub to select project and issues and at least write back voted story points.

Probably this issue has to be spited in several issues  and needs first investigation if API of GitHub supports all required things.

**Comment by SponsoredByPuma** [comment]
Should we just add the the voted story points to the description?
Maybe we could add a little text at the end of the description something like this:

Story Points voted on Diveni.io: 5

**Comment by stritti** [comment]
That is a good question.
At least we have to be sure we can read/write it as save as possible. Probably we need to add some markdown elements around.
