### ISSUE TITLE
Wizard based creation of session

### ISSUE THREAD

**Issue by stritti** [Sybit-Education/Diveni#486]
**Is your feature request related to a problem? Please describe.**

The page for creation of session is rather long. We should consider to create a wizard which guides step by step and for example distinguish what to show as additional step if external issue tracker is connected.

**Describe the solution you'd like**

Easy to use wizard to be guided on creation of session.

**Comment by Dan1elBox** [comment]
Hey @stritti, do you have a good wizard form library/component in mind that we could use for this, or should we create it completely custom/from scratch?

**Comment by stritti** [comment]
Hey @Dan1elBox Bootstrap seems to have no own component. Maybe this one could help: https://www.npmjs.com/package/vue3-steppy
