### ISSUE TITLE
Some graphical components/elements do not load

### ISSUE THREAD

**Issue by G1t-Happens** [Sybit-Education/Diveni#496]
During the light mode/theme, some of the components/elements no longer load correctly. 
Maybe in connection with PR: Improved Menubar #488 ?

![error-notloaded](https://github.com/Sybit-Education/Diveni/assets/44774729/29918ab6-73c2-495d-be4e-8ded21340222)

**Comment by stritti** [comment]
I will check this!

**Comment by G1t-Happens** [comment]
@stritti I think the issue was fixed with the last PR:  Fix: button layout #497 . 
However, I have found a few more differences. 
On the landing page, the boxes look somewhat different than before:

![Boxes](https://github.com/Sybit-Education/Diveni/assets/44774729/2f80bcca-f0bd-4d95-ac07-0150c467fe83)
![BoxesV2](https://github.com/Sybit-Education/Diveni/assets/44774729/e37a7566-5cd0-4fff-ad79-c7bb5651eddb)

And on the prepare page, the top box looks somewhat different:
![Now](https://github.com/Sybit-Education/Diveni/assets/44774729/db332264-8ab4-4c3c-85a3-0e2906261a3c)

Before:
![Before](https://github.com/Sybit-Education/Diveni/assets/44774729/5dfef153-c952-4a95-b417-367e19728c7b)

If that's intentional, please ignore my comment 😃

**Comment by stritti** [comment]
That wasn't the idea 🤡
Thanks for showing. There went something wrong on merges I think. Hopefully I fixed that in the PR now.
