### ISSUE TITLE
Filtering User Stories throws error

### ISSUE THREAD

**Issue by SponsoredByPuma** [Sybit-Education/Diveni#714]
**Describe the bug**
When filtering user stories while using jira/gitlab/github you get errors in the console.

**To Reproduce**
1. use issue tracker
2. filter stories
3.  See error

**Expected behavior**
No error should happen, as well as not updating the story list

**Comment by Dan1elBox** [comment]
It looks like PR: #687 has already fixed this issue. Issue will be reopened if the problem occurs again.
